# Generated by Django 5.2.12 on 2026-06-08 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='Telegram ID пользователя')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telegram', models.CharField(max_length=100, verbose_name='Telegram @username')),
                ('partnership_type', models.CharField(choices=[('advertising', 'Реклама'), ('blogger', 'Блогер'), ('partnership', 'Партнёрство'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип сотрудничества')),
                ('description', models.TextField(verbose_name='Описание предложения')),
                ('social_links', models.TextField(blank=True, help_text='Введите ссылки через запятую', verbose_name='Ссылки на соцсети')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('approved', 'Одобрено'), ('rejected', 'Отказано')], default='pending', max_length=50, verbose_name='Статус')),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответственный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка на сотрудничество',
                'verbose_name_plural': 'Заявки на сотрудничество',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='PartnershipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], max_length=20)),
                ('sender_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='news.partnership')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
