# Generated by Django 5.2.12 on 2026-06-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('deal_id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID сделки')),
                ('seller_id', models.BigIntegerField(blank=True, db_column='seller', null=True, verbose_name='Продавец (Telegram ID)')),
                ('buyer_id', models.BigIntegerField(blank=True, db_column='buyer', null=True, verbose_name='Покупатель (Telegram ID)')),
                ('asset_name', models.TextField(blank=True, db_column='item', null=True, verbose_name='Название NFT')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Сумма сделки')),
                ('commission', models.FloatField(blank=True, null=True, verbose_name='Комиссия')),
                ('currency', models.TextField(default='RUB', verbose_name='Валюта')),
                ('status', models.TextField(default='awaiting', help_text='awaiting → payment_pending → paid → item_sent → completed / disputed / cancelled', verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created', verbose_name='Создана')),
                ('completed_at', models.DateTimeField(blank=True, db_column='completed', null=True, verbose_name='Завершена')),
                ('payment_method', models.TextField(default='internal', verbose_name='Способ оплаты')),
                ('payment_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий платежа')),
                ('payment_address', models.TextField(blank=True, null=True, verbose_name='Адрес для on-chain оплаты')),
                ('payment_amount', models.FloatField(blank=True, null=True, verbose_name='Сумма on-chain')),
                ('paid_tx_hash', models.TextField(blank=True, null=True, verbose_name='Hash транзакции')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено')),
                ('disputed_at', models.DateTimeField(blank=True, null=True, verbose_name='Переведено в спор')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'db_table': 'deals',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
