# Generated by Django 5.2.12 on 2026-06-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.BigIntegerField(db_column='user_id', primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('username', models.TextField(blank=True, null=True, verbose_name='Username')),
                ('first_name', models.TextField(blank=True, null=True, verbose_name='Имя')),
                ('last_name', models.TextField(blank=True, null=True, verbose_name='Фамилия')),
                ('is_admin', models.BooleanField(db_column='is_admin', default=False, verbose_name='Администратор')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('premium_until', models.DateTimeField(blank=True, null=True, verbose_name='Premium до')),
                ('premium_granted_by', models.BigIntegerField(blank=True, null=True, verbose_name='Premium выдан (admin ID)')),
                ('premium_granted_at', models.DateTimeField(blank=True, null=True, verbose_name='Premium выдан')),
                ('premium_duration_days', models.IntegerField(default=0, verbose_name='Длительность Premium (дни)')),
                ('card_details', models.TextField(blank=True, null=True, verbose_name='Реквизиты карты')),
                ('card_currency', models.TextField(default='RUB', verbose_name='Валюта карты')),
                ('ton_wallet', models.TextField(blank=True, db_column='ton_wallet', null=True, verbose_name='TON кошелёк')),
                ('ton', models.TextField(blank=True, null=True, verbose_name='TON (альтернативный)')),
                ('referral_code', models.TextField(blank=True, null=True, verbose_name='Реферальный код')),
                ('referred_by', models.BigIntegerField(blank=True, null=True, verbose_name='Пригласил (Telegram ID)')),
                ('referral_earnings', models.FloatField(default=0, verbose_name='Заработано на рефералах')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Кол-во отзывов')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('balance_rub', models.FloatField(db_column='balance_RUB', default=0, verbose_name='Баланс RUB')),
                ('balance_usd', models.FloatField(db_column='balance_USD', default=0, verbose_name='Баланс USD')),
                ('balance_eur', models.FloatField(db_column='balance_EUR', default=0, verbose_name='Баланс EUR')),
                ('balance_byn', models.FloatField(db_column='balance_BYN', default=0, verbose_name='Баланс BYN')),
                ('balance_uah', models.FloatField(db_column='balance_UAH', default=0, verbose_name='Баланс UAH')),
                ('balance_kzt', models.FloatField(db_column='balance_KZT', default=0, verbose_name='Баланс KZT')),
                ('balance_uzs', models.FloatField(db_column='balance_UZS', default=0, verbose_name='Баланс UZS')),
                ('balance_ton', models.FloatField(db_column='balance_TON', default=0, verbose_name='Баланс TON')),
                ('balance_usdt', models.FloatField(db_column='balance_USDT', default=0, verbose_name='Баланс USDT')),
                ('balance_stars', models.FloatField(db_column='balance_STARS', default=0, verbose_name='Баланс STARS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
